#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "motioneye"
name = "motionEye"
description.en = "Web frontend for the motion daemon"
description.fr = "Web frontend for the motion daemon"

version = "0.43.1b1~ynh1"

maintainers = ["solazdev"]

[upstream]
license = "GPL-3.0"
userdoc = "https://github.com/motioneye-project/motioneye/wiki"
code = "https://github.com/motioneye-project/motioneye"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "500M"
ram.build = "5120M"
ram.runtime = "1024M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/motioneye"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    # [install.password]
    # # this is a generic question - ask strings are automatically handled by YunoHost's core
    # # Note that user-provided passwords questions are not automatically saved as setting
    # help.en = "Use the help field to add an information for the admin about this question."
    # help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    # type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/motioneye-project/motioneye/archive/refs/tags/0.43.1b1.tar.gz"
        # sha256 = "047f2e11ceb9f8af3f07bde99c9f520bf0b78485bcedfdaa1424d75cb76b30c5"
        extract = false
        rename = "source.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8765

    [resources.apt]
    packages = "ca-certificates, curl, python3, python3-dev, python3-venv, libcurl4-openssl-dev, gcc, libssl-dev, motion, ffmpeg, v4l-utils, libssl-dev, libcurl4-openssl-dev, libjpeg-dev, zlib1g-dev, libffi-dev, libzbar-dev, libzbar0"
